// src/pages/api/lead.ts
// Handles primary lead/inquiry form submissions (name, email, company, goal, etc.).
// DO NOT edit this file per client — update src/lib/email.config.ts instead.

import type { APIRoute } from 'astro';
import { Resend } from 'resend';
import mailchimp from '@mailchimp/mailchimp_marketing';
import { EMAIL_CONFIG } from '~/lib/email.config';

const resend = new Resend(import.meta.env.RESEND_API_KEY);

if (EMAIL_CONFIG.mailchimp.enabled) {
  mailchimp.setConfig({
    apiKey: import.meta.env.MAILCHIMP_API_KEY,
    server: import.meta.env.MAILCHIMP_SERVER_PREFIX,
  });
}

export const POST: APIRoute = async ({ request }) => {
  try {
    const data    = await request.formData();
    const name    = data.get('name')?.toString().trim()    ?? '';
    const email   = data.get('email')?.toString().trim()   ?? '';
    const company = data.get('company')?.toString().trim() ?? '';
    const phone   = data.get('phone')?.toString().trim()   ?? '';
    const goal    = data.get('goal')?.toString().trim()    ?? '';
    const source  = data.get('source')?.toString().trim()  ?? '';

    if (!email || !name) {
      return new Response(JSON.stringify({ error: 'Name and email are required.' }), { status: 400 });
    }

    // Internal notification
    try {
      await resend.emails.send({
        from: EMAIL_CONFIG.from.notifications,
        to: EMAIL_CONFIG.notify,
        subject: `New lead: ${company || name}`,
        html: `
          <h2>New Lead Form Submission</h2>
          <p><strong>Name:</strong> ${name}</p>
          <p><strong>Email:</strong> ${email}</p>
          ${company ? `<p><strong>Company:</strong> ${company}</p>` : ''}
          ${phone   ? `<p><strong>Phone:</strong> ${phone}</p>` : ''}
          ${goal    ? `<p><strong>Goal:</strong> ${goal}</p>` : ''}
          ${source  ? `<hr><p style="color:#888;font-size:13px"><strong>Source</strong><br>${source.replace(/\n/g, '<br>')}</p>` : ''}
        `,
      });
    } catch (err) {
      console.error('Resend notify error:', err);
    }

    // Confirmation to sender
    try {
      await resend.emails.send({
        from: EMAIL_CONFIG.from.hello,
        to: email,
        subject: EMAIL_CONFIG.copy.lead.confirmSubject,
        html: EMAIL_CONFIG.copy.lead.confirmBody(name, company, EMAIL_CONFIG.brand.url),
      });
    } catch (err) {
      console.error('Resend confirm error:', err);
    }

    // Always add leads to Mailchimp
    if (EMAIL_CONFIG.mailchimp.enabled) {
      try {
        await mailchimp.lists.addListMember(import.meta.env.MAILCHIMP_AUDIENCE_ID, {
          email_address: email,
          status: 'subscribed',
          merge_fields: {
            FNAME:   name.split(' ')[0],
            LNAME:   name.split(' ').slice(1).join(' '),
            COMPANY: company,
          },
          tags: [...EMAIL_CONFIG.mailchimp.defaultTags, 'lead-form'],
        });
      } catch (err: any) {
        console.error('Mailchimp lead error:', err?.response?.body ?? err);
      }
    }

    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    console.error('Lead API error:', err);
    return new Response(JSON.stringify({ error: 'Something went wrong. Please try again.' }), { status: 500 });
  }
};
